### ISSUE TITLE
Add links with icon to tables

### ISSUE THREAD

**Issue by krumdp** [krishnanlab/geneplexus_app#11]
Using a URL icon instead of a link reach out to the following websites with the term being clicked
			Predictions - https://www.ncbi.nlm.nih.gov/gene/ - Use Entrez id
			GO - http://amigo.geneontology.org/amigo/term/
			Disease - https://disease-ontology.org/?id

**Comment by billspat** [comment]
Links are in place but design decision not to use icons.
