### ISSUE TITLE
Job status has strange string

### ISSUE THREAD

**Issue by ChristopherMancuso** [krishnanlab/geneplexus_app#122]
When the job is first submitted it submitted in the Status column, but after some time (maybe while the job is running) it has a string that says something like INFO:mljob.geneplexus:3. run_SL... features=%s, features

If this is indeed for a running job, maybe just change the string to say Running?

**Comment by ChristopherMancuso** [comment]
@billspat This issue seems to be closed, but the status messages don't seem to be updated to the last message above. Are they in a new issue?

**Comment by ChristopherMancuso** [comment]
Also one thing I noticed it that before the message says completed, it looks like there is a space separated list of numbers printed out. Not sure what those number represent

**Comment by billspat** [comment]
@ChristopherMancuso  to answer your question above the numbers shouldn't be in there.    I captured the output of a `curl`  into the log and I'll suppress that output.   I'm glad you saw them (I never did).  

As a fix for this issue, would you like this merged into the main geneplexus.net site for the reviewers or hold it with our other changes (in the `dev` branch) for post-review but pre-publication?

**Comment by ChristopherMancuso** [comment]
I don't think there is a reason to push this to the main site until after it is reviewed
