### ISSUE TITLE
code tests

### ISSUE THREAD

**Issue by billspat** [krishnanlab/geneplexus_app#126]
At this stage it's crucial to test changes and fixes before pushing to azure, so this issue is here to link to initial build of the testing harness based on https://flask.palletsprojects.com/en/2.0.x/testing/

**Comment by jacobnewsted** [comment]
Beginning work on this. The setup is going to be a combination of:

- [pytest](https://docs.pytest.org/)
- [pytest-selenium](https://pytest-selenium.readthedocs.io/en/latest/user_guide.html)
- [pytest-flask](https://pytest-flask.readthedocs.io/en/latest/)

I am working on getting the general setup to work. There is an issue with starting the server which I am working out right now

**Comment by jacobnewsted** [comment]
Now have more complete docs and an initial test on 6064ab1ede7e172b4193aba7c5c1f78cd1906ffa

**Comment by billspat** [comment]
features and issues deferred for rewrite --closing here.
