### ISSUE TITLE
It would be nice to be able to see more than 50 nodes if many have high probability

### ISSUE THREAD

**Issue by billspat** [krishnanlab/geneplexus_app#154]
need some clarification

 - what does is mean "many have high probability"
 - can we simply set a fixed upper limit and let the slider do the rest?
 

- [ ] determine the upper limit due to performance
- [ ] change how the graph is created to have all of those nodes
- [ ] adjust the slider to the probabily of the 50th node and show just 50 nodes to begin with
- [ ] set the slider low end to be the lowest probability of the last node to be displayed

**Comment by billspat** [comment]
@ChristopherMancuso let us know that 50 is enough and that's what the limit is currently, and we show 20 nodes when the graph is first loaded.   I would like to open the question again, now that we have sliders if you want to increase that upper limit to something like 100.

**Comment by ChristopherMancuso** [comment]
this is a tricky on to answer. There is two factors at play. First, is can a graph with more nodes still look good enough to give informative information (i..e have it not turn into the dreaded hairball). Second, how much data can go on the web page with out it causing loading problems (if the network is too big and it crashes or slows down looking at the gene predictions, that is not good).

This is all compounded by the fact the network density between different network types is so variable. For instance, looking at 100 nodes in BioGRID is going to be way different than looking at 100 nodes in GIANT-TN (I think). It is great that 200 nodes in GIANT-TN works on your computer Jacob.

**Comment by ChristopherMancuso** [comment]
@jacobnewsted in the current version of geneplexus, are you setting the force constants differently for each network?

**Comment by billspat** [comment]
this issue was something we discussed prior to submitting the manuscript for review, and we didn't revisit this as part of changes to address reviewer comments after the paper was accepted with revisions.   The reviewers did not bring this up and it's on not on the google doc of changes, so I'm taking this out of this milestone.    @ChristopherMancuso should this be closed outright, or saved as a question for the next version of geneplexus web server?

**Comment by ChristopherMancuso** [comment]
@billspat Let's save it for the next version of the web server

**Comment by billspat** [comment]
features and issues deferred for rewrite --closing here.
