### ISSUE TITLE
Site layout padding/size

### ISSUE THREAD

**Issue by billspat** [krishnanlab/geneplexus_app#158]
Make the padding in the white areas on all pages consistent. For instance, the Jobs page has a lot of padding on the left, right (not equal to left), and top. Most other pages have smaller but reasonable paddings. The Landing page has almost no padding on the right and bottom. Suggestions on padding on all pages:
 - Set the padding on the top as much as Help or About.
 - Set the left and right paddings equal to the right padding of the Jobs page

In addition all the text throughout the website can be reduced by one (or even two font sizes).

**Comment by jacobnewsted** [comment]
Finished this in latest commit. Closing
