### ISSUE TITLE
affix left side column scroll (job form)

### ISSUE THREAD

**Issue by billspat** [krishnanlab/geneplexus_app#162]
From Arjun: Is it possible to independently scroll the white area and keep the gray area as is? Don’t bother if this is hard to do.

**Comment by billspat** [comment]
@ChristopherMancuso  we gave this a try but we believe it may required changes to the layout to accomplish so we'd like to move this to a future milestone.

**Comment by ChristopherMancuso** [comment]
That sounds good to me

**Comment by billspat** [comment]
features and issues deferred for rewrite --closing here.
