### ISSUE TITLE
Enhancement to datatables layout

### ISSUE THREAD

**Issue by billspat** [krishnanlab/geneplexus_app#163]
All tables (Input Genes in Current Geneset and all the tables in various Results tabs)
 - The “Show 10 more …” buttons:
   - Right-align it exactly with the table below.
   - Horizontally align it exactly with the “Search + text box” on the left (with some space between these buttons and the table below).
   -  Parts of the dropdown when clicking on the “10 rows” button are hidden behind the header of the table below. (see image below)  or in other words, when datatables are half-width, clicking on the # of rows selector, the drop down goes behind the column headers   ‘Show 10 rows’ doesn’t render properly. 

   - If it’s possible to do fast: add a TSV option (to download a tab-separated file of the table).

- In the gene table, left-align the contents of columns 1 and 2 exactly with the header.

- Pagination “First / Previous / …”
  Change style to match the other button styles. Suggest something like an inversion of the colors of the “Show 10 more” 
buttons: black text, light gray fill.  & Horizontally align exactly with “Showing … to … of … entries”.

![gp-datatables-issue](https://user-images.githubusercontent.com/266479/156607352-eff540ca-a7e6-4c59-9c3e-d4165edaca66.png)

**Comment by jacobnewsted** [comment]
<img width="562" alt="Screen Shot 2022-03-10 at 1 37 38 PM" src="https://user-images.githubusercontent.com/26586050/157732068-d18dc597-b5dc-40ca-88df-33284dec2e9b.png">
<img width="1167" alt="Screen Shot 2022-03-10 at 1 37 46 PM" src="https://user-images.githubusercontent.com/26586050/157732069-c5279a06-e755-4a09-9e74-1e49fc434020.png">
Added as per instructions above

**Comment by jacobnewsted** [comment]
This specific issue is done, I will make a new one for the padding issue
