### ISSUE TITLE
edits to Job submit form (input panel on the left)

### ISSUE THREAD

**Issue by billspat** [krishnanlab/geneplexus_app#167]
- sidenav layout: the panel seems to have become narrower than it was earlier in the afternoon (now the ‘Submit’ button at the bottom is sticking out of the panel).  the Submit button stays wide while the "edit loaded genes" button shrinks with sidenav column.    Either change the layout and make the button smaller (or some combination)

 - Add the text “ [Help]” to the “?” icon text for popovers for the items  3. Select Molecular Network, 4. Select Feature Type, 5. Select Negative Gene Class  ( see #155 ) 

- Overall help texts: some end with a period `.` and few don’t - make consistent 

- "1. Enter/Load Gene Set"
  - Change “Enter/Load Gene Set” to “Enter/Upload Gene List”.
  - Change “?” icon text to: “Manually enter a gene list or upload a gene list file. Click to see examples for both. [Help]”
  - When a geneset has already been loaded, the text “Add Genes” changes to “Edit Loaded Genes”. To make it clear that the user can not only edit their preloaded genes but also clear their input and enter a new gene set, let’s change the text to “Edit Loaded Genes / Add New Genes”.
  - An external user mentioned that having a number 1 on this item seemed weird when it was the only think that was showing.  
  
- "2. Job Name"
  - Move “Job Name” below and make it item number 5, just above email. That way, the two optional items will be at the end and together.
  - Change “?” icon text to: A unique job identifier will be auto-generated. To make the model easy to identify, you can add an optional prefix to the job ID by typing text into the box below. Max 32 characters; anything longer will be truncated.
  - Change text above text box to: “(Optional) Add a prefix to the job name”.

  - The auto-generated unique string (next to the optional text box) is not aligned with the hyphen on the same line.

  - Remove the gray text “Optional” inside the text box to be consistent with the email text box.

- Center-align the Submit button to the gray panel or make it as wide as the “E”.

**Comment by billspat** [comment]
@jacobnewsted if anything on this list isn't complete, please create a new issue with those things yet to do, and close this one?

**Comment by jacobnewsted** [comment]
Going to close this and condense the remaining issues into issue #155
