### ISSUE TITLE
data tables order for results

### ISSUE THREAD

**Issue by billspat** [krishnanlab/geneplexus_app#178]
split off from #168 

## Gene Prediction table

make “Rank” the first column on the left == Move Rank to column 1 and keep the width to the minimum.

Make the widths of columns ‘Entrez’, ‘Symbol’, ‘Probability’, ‘Known/Novel’, and ‘Class-Label’ the same and snug.

- Make the ‘Name’ column use the remaining width.

Similarities to BPs/Diseases table: make “Rank” the first column on the left.

**Comment by jacobnewsted** [comment]
Current look (for one tab, the rank size will be similar in the other tables)
<img width="1652" alt="Screen Shot 2022-04-13 at 12 44 31 PM" src="https://user-images.githubusercontent.com/26586050/163229794-f61a98f5-ee9e-47ea-8882-b5ffacec2f4c.png">

**Comment by jacobnewsted** [comment]
there are issues with changing column sizes on the other 3 tables causing the table to colapse into 1/4th of the screen so we will table that for now and submit this

**Comment by billspat** [comment]
closed with PR #202
