### ISSUE TITLE
make new subscription for this project

### ISSUE THREAD

**Issue by ChristopherMancuso** [krishnanlab/geneplexus_app#180]
This project may need its own Azure subscription. Along those lines maybe need to increase the quota for containers. Also, would it be good to create one subscription for every project in Arjun's group or have each project get its own subscription. For example if the pip python package needs some cloud storage of the data, would that be a separate subscriptions. What about web server for Nat's old project?

**Comment by billspat** [comment]
I suggest that your lab request a new sub and provide the account number so you will own it.  Then invite us as members.    You will need to provide an approximate monthly spend and so I'm adding to this issue the task of determing a budget.  I will look at our main geneplexus.net account and the various test accounts to determine that.      @ChristopherMancuso  would you please run several jobs to simulate some basic level of users? That will give us more cost data to help our estimate.

**Comment by billspat** [comment]
- [ ] run several jobs to add data for costs
- [ ] take cost data from geneplexus.net and various dev resource groups to create monthly cost estimate
- [ ] Arjun/Chris complete the form that is linked in this page https://tech.msu.edu/network/cloud-services/  which requires an account number and estimated monthly spend

**Comment by ChristopherMancuso** [comment]
I can run some jobs. For the subscription, would that be just for geneplexus or one for the krishnanlab and Arjun would then make different resource groups for his various projects?

**Comment by billspat** [comment]
@ChristopherMancuso filed a ticket with IT Services two weeks ago to create a new subscription.  Chris would you add ac comment here that includes the response and the date you got it?   thank you!

**Comment by ChristopherMancuso** [comment]
I submitted the initial request on 3/22/22.
I received a message on 3/28/22 that they have resource constraints and cannot provide a timeline for completion
On 4/5/22 they changed the estimated completion data on the ticket too 5/31/22

**Comment by billspat** [comment]
this is blocked so moving to the next milestone.

**Comment by billspat** [comment]
since we don't have an ETA,  setting this aside for 'future direction' until we do

**Comment by billspat** [comment]
since the Krishnan lab has moved to [University of Colorado Anschutz Medical Campus](https://www.cuanschutz.edu/) , we won't be creating a new subscription at MSU, we will continue to use our DMA/developement subscription until the team at CU takes over the app sometime in January 2023
