### ISSUE TITLE
method to manage container instances

### ISSUE THREAD

**Issue by billspat** [krishnanlab/geneplexus_app#182]
Container instances (ACI) may hang around after a job is completed, and Azure has a quota of 100 ACIs per subscription per region. 

To ensure we don't hit that quota, need a quick way to check the number of ACIs and delete those that are 'completed' (when they are complete the job output data is all put in storage so the ACI is not longer needed).

**Comment by billspat** [comment]
if we return to using Logic App to create ACI, this issue is important and the approach would be to find a mechanism in the logic app to wait for the ACI to complete and then delete it.  But we are switching to Azure functions with #218, so closing this issue as obsolete.

**Comment by billspat** [comment]
@ChristopherMancuso  -finally a job clean-up process.   Would you please run some test jobs and check the portal to ensure the job containers are deleted after completion?

**Comment by ChristopherMancuso** [comment]
@billspat I ran 5 jobs let me know if you need more. I added some information on the job names in the last email I sent. This is great this might be working!
