### ISSUE TITLE
About Help edits (references)

### ISSUE THREAD

**Issue by billspat** [krishnanlab/geneplexus_app#187]
Change/Update some references in the Help section

BioGRID add the following reference 

Oughtred,R., Stark,C., Breitkreutz,B.-J., Rust,J., Boucher,L., Chang,C., Kolas,N., O’Donnell,L., Leung,G., McAdam,R., et al. (2019) The BioGRID interaction database: 2019 update. Nucleic Acids Research, 47:D529–D541

STRING and STRING-EXP remove the old reference and replace it with

Szklarczyk,D., Gable,A.L., Lyon,D., Junge,A., Wyder,S., Huerta-Cepas,J., Simonovic,M., Doncheva,N.T., Morris,J.H., Bork,P., et al. (2019) STRING v11: protein–protein association networks with increased coverage, supporting functional discovery in genome-wide experimental datasets. Nucleic Acids Research, 47:D607–D613.

**Comment by jacobnewsted** [comment]
Merged into dev
