### ISSUE TITLE
change parameters for Cross Validation thresholds and results as displayed

### ISSUE THREAD

**Issue by billspat** [krishnanlab/geneplexus_app#188]
Set the default parameters to the following:
- Minimum number of positive genes is 15
- Number of folds is 3

this can be changed directly in `geneplexus.py`; use as an input parameter to the function and set default for that input parameter. 

On results page: 
Change the output so each value of the 3 folds is displayed instead of just the median

**Comment by billspat** [comment]
this is achange of how we report and present the log2(auPRC/prior) values from single value ( scalar float) to list of values which changes the job output template.  It's a minor change but previous jobs  (that only output a scalar) no have the wrong wording and output method.   Do we change the templates to accommodate previous jobs  (with `if` block) or remove them all?

**Comment by ChristopherMancuso** [comment]
Results for 3-fold cross validation in terms of _log2(auPRC/prior)_ : **1.04**, **1.25**, **0.53**

**Comment by ChristopherMancuso** [comment]
the tool tip here needs to change bit where 20 needs to be replaced by 15 as well

**Comment by billspat** [comment]
Thank you!  yes the tool tip is already changed.

**Comment by ChristopherMancuso** [comment]
@billspat @jacobnewsted Along those lines, some text in the Help section will have to change in the section "Information at the top"

Please change (the formatting was lost here)
"If the number of genes in the positive class is greater than 20, then the median value of the 5-fold cross validation performance is displayed in terms of log2(auPRC/prior)"

To
"If the number of genes in the positive class is greater than 15, then the results of 3-fold cross validation performance is displayed in terms of log2(auPRC/prior)"

**Comment by billspat** [comment]
addressed Chris comment above, closing.
