### ISSUE TITLE
re-organize model form to help users choose options

### ISSUE THREAD

**Issue by billspat** [krishnanlab/geneplexus_app#189]
Helping users navigate which options they should choose...

(from Chris): I think the box in which the users chose the network parameters and enter their email and jobname should be rearranged to help them with choosing the parameters. 

1. Top of box says “For guidance on which parameters to chose, please see the Help page” and then link to the Help page section
2. Selector box to choose network
3. Selector box to choose features
4. Selector box to choose GSC
5. Some text that says “The following two boxes are optional”
6. Text box for adding job name
7. Text box for adding email

**Comment by jacobnewsted** [comment]
The original issue didn't rearrange anything but I did add the messages. I think this is suitable but if we want to rearrange things we can still do that
<img width="387" alt="Screen Shot 2022-04-12 at 3 49 34 PM" src="https://user-images.githubusercontent.com/26586050/163042113-796d0486-e0a7-4293-ac72-7f56fa9da119.png">

**Comment by billspat** [comment]
Jacob mentions that the form did not require re-arranging.  I believe it was re-arranged in the dev branch last month but the version in main (on the main website) had the job name at the top.  Closing the issue.
