### ISSUE TITLE
on results page, graph tab section is not full page-width

### ISSUE THREAD

**Issue by billspat** [krishnanlab/geneplexus_app#196]
on the jobs results page ( `views.job(jobname)` ), the 'network graph' tab is not full page width but narrower than the other tabs ( which have tables).  It's not bad on Chrome/Firefox but about 50% width on Safari. 

some experimenting shows that changing

```html
<div class="tab-pane fade active show" id="netgraph">
    <div class="table_container">
```
to 

```html
<div class="tab-pane fade active show" id="netgraph">
    <div class="row">
```

solves the problem on all recent browsers but it does stretch out the sliders to full width but still functional

**Comment by jacobnewsted** [comment]
should we also add in the issue with the Gene Prediction tab being also not full width in here?
