### ISSUE TITLE
minor text changes per Chris

### ISSUE THREAD

**Issue by billspat** [krishnanlab/geneplexus_app#203]
1. Help page: 

second figure caption:  if you could add a link to the Bioinformatics paper on the text that has the paper title that would be great. Just like the first figure caption

2. sidenav Job form:
I was also thinking of adding text directly to the box that the user selects the job parameters that says something like

For more information on which parameters to select, see the Help section".  ( and not just have this text put in each tool tip, since the link in the tooltip all goes to the top of the page.

**Comment by billspat** [comment]
I took a hybrid approach to this and the previous issue #189 

- there is a sentence at beginning of page linking to help#guidelines-for-best-settings , and inside tool tips for each option are links to the specific sections in help :  n`choosing-a-molecular-network`, `choosing-a-way-to-represent-network-features`. etc/

**Comment by ChristopherMancuso** [comment]
This looks great!

**Comment by billspat** [comment]
thank you Chris! this is already in dev, so closing issue
