### ISSUE TITLE
Clicking popovers scrolls up

### ISSUE THREAD

**Issue by jacobnewsted** [krishnanlab/geneplexus_app#207]
Reproduction steps:
 - Scroll down (but not so far that all tooltips disappear)
 - Click on a tooltip
 -  The screen scrolls up

**Comment by jacobnewsted** [comment]
Fixed in 17c784882d702fa9d9f221eb1c06329bbfe2b545

**Comment by billspat** [comment]
@jacobnewsted fixed with new pop-over system
