### ISSUE TITLE
Update links to published paper on production website

### ISSUE THREAD

**Issue by billspat** [krishnanlab/geneplexus_app#213]
From Arjun: 

Can we please add our NAR paper to the webserver at multiple places?

On the landing page, as the last item under “Using GenePlexus”:

Cite GenePlexus: 

**Mancuso CA, et al., (2022) GenePlexus: a web-server for gene discovery using network-based machine learning, Nuc. Acids Res., [doi:10.1093/nar/gkac335.](https://doi.org/10.1093/nar/gkac335)**

Add to the Help and About pages, formatting the citation exactly like other references on those pages (including the paper title being linked to the journal page).

About: Under a new heading “Citation” at the end of the page.

Help: New subheading “Web-server” under “References” (above “Networks”).

**Comment by billspat** [comment]
@arjunkrish @ChristopherMancuso  : I added the citation to the product site.  When have time would you take a look to ensure it was what you described?  Thank you!  

 - https://www.geneplexus.net
 - https://www.geneplexus.net/help#references
 - https://www.geneplexus.net/about#citation

**Comment by ChristopherMancuso** [comment]
Looks good to me
