### ISSUE TITLE
Manage emails with SSO

### ISSUE THREAD

**Issue by jacobnewsted** [krishnanlab/geneplexus_app#230]
Because SSO logins do not ensure an email is linked to the account used for SSO, we need a mechanism for users that use SSO sign on to know that they can fill out an email in their profile. The system needs

- A method to let the user know, after using SSO, that they do not have an email attached to their account
- A method to automatically populate the notification email input box if the user is signed in and has an email attached to their account

**Comment by billspat** [comment]
features and issues deferred for rewrite --closing here.
