### ISSUE TITLE
Logging in during detailed results freezes screen

### ISSUE THREAD

**Issue by jacobnewsted** [krishnanlab/geneplexus_app#238]
Ensure you are not logged in
Steps to reproduce:
 - Successfully run a job
 - Go to the detailed results
 - Try to log in using the button in the top right corner
 - Screen fades and freezes

**Comment by billspat** [comment]
confirm this bug ( in the dev branch after merging )

**Comment by billspat** [comment]
this should be fixed with #258

**Comment by billspat** [comment]
features and issues deferred for rewrite --closing here.
