### ISSUE TITLE
result URL with invalid id errors instead of 404

### ISSUE THREAD

**Issue by billspat** [krishnanlab/geneplexus_app#241]
If you put a string that is not a job id in the result route 

`http://127.0.0.1:5000/result/x`

The app returns an error 

```
AttributeError
AttributeError: 'NoneType' object has no attribute 'description'
```

In addition, any jobid that is not saved as part of a result will also return an error.  This means that is a result is deleted but the user tries the URL, the output is an error.
In addition, If you run a job when not logged in, no 'result' record is saved.  The output of the job is still available via the `jobs` route eg. 
`http://127.0.0.1:5000/jobs/anon819-qxb6y3vi`

it's the same error (because of course there is no corresponding result id since no result record was created)

Solution is to check the 'result' exists and return 404 instead of crash.  however, for anonymous jobs, do we want to still show the output  (especially given suggested solution to #240 to only show results on a the `/results/` route )

**Comment by jacobnewsted** [comment]
Do we want to have a separate page for either of these issues (rather than a 404) or do we want to just flash a message and redirect someplace?

**Comment by jacobnewsted** [comment]
Closed with pull request
