### ISSUE TITLE
current app version can't handle real sized genesets ( ~ 1k genes)

### ISSUE THREAD

**Issue by billspat** [krishnanlab/geneplexus_app#262]
this is the same issue as #256  where becuase of browser cookie size limits can't store a good sized geneset in cooke.  this issue is to fix it in the current production version since the branch that was fixed in is not ready for production 

discovered that you could use [flask-session2](https://pypi.org/project/flask-session2/) which requires an upgrade from flask 1 to flask 2.2 which could have repercussions other libs and for the app itself.  

see current dev requirements file : https://github.com/krishnanlab/geneplexus_app/blob/dev/requirements.txt

and the commit 04643a3cb8228cb3676a5ed2c2c08dcceae8952b for the PR.  This uses a db backed session which 
which contains several libs for user account database which are not needed for production (flask dance, sqlalchemy etc), would use filesystem instead `app.config['SESSION_TYPE'] = 'filesystem'

**Comment by billspat** [comment]
Revisiting this and for the  main branch.   the solution here is to use https://pypi.org/project/flask-session2/ and a backend.  We aren't using a database so need to use either the file system backend.  The downside for this is that files could grow unless this lib will prune sessions as needed.  Could potentially use sqlite with the 'peewee' library which is much lighter than Flask-sqlalchemy but again need a method to determine the system is culling sessions.

**Comment by billspat** [comment]
this fix works for me for a 500 element geneset.  @ChristopherMancuso  would you please try the app with one of your "large" genesets ?

**Comment by ChristopherMancuso** [comment]
@billspat a list of 2000 genes worked great
