### ISSUE TITLE
rename download validation data button

### ISSUE THREAD

**Issue by ChristopherMancuso** [krishnanlab/geneplexus_app#268]
![download_genes](https://github.com/krishnanlab/geneplexus_app/assets/28111913/125be6fe-81d5-472e-8e2c-93ef73019b61)

In input genes, change download button name to something like "Download Input Genes". Writing validation data makes some people think they would be getting back the auPRC metric for each gene list.

**Comment by billspat** [comment]
![image](https://github.com/krishnanlab/geneplexus_app/assets/266479/e98de06f-a2ae-4477-afe2-56ea7c8ccfe5)
