### ISSUE TITLE
privacy policy?

### ISSUE THREAD

**Issue by billspat** [krishnanlab/geneplexus_app#54]
Since we collect email address to notify job status, and currently we are saving this email address with the job, and we use cookies to track jobs, AND plan to have user accounts, we should have a minimal privacy policy.   For example: 

   "You agree to allow us to collect and store your email address if you create an account, or add the optional notification address when submitting jobs.  We agree never to share your information outside of the application, and we will never use this information to contact you unsolicited or without your consent (e.g. for communication for help requests or professional conversation related to this project)."   

Are there examples of other privacy policies for similar applications  that accept email addresses or user accounts?

**Comment by billspat** [comment]
here is an example policy from the European Bioinformatics Institute for their bio-complex database: 

https://www.ebi.ac.uk/data-protection/privacy-notice/embl-ebi-public-website

**Comment by billspat** [comment]
@ChristopherMancuso  I added this one in March.  What do you think?  Do you feel it's necessary?  I am thinking it would be a section in the "about" page, and the link "privacy policy" could be on the bottom of the page.

**Comment by ChristopherMancuso** [comment]
I think something like this would be good to have

**Comment by billspat** [comment]
thanks @ChristopherMancuso , I started a draft of this to get it into place but really needs editing. Do you have time to review this morning?   I put it up on our dev website but since it's in a branch it can be removed easily.     https://geneplexusdev2202.azurewebsites.net/about#privacypolicy

**Comment by ChristopherMancuso** [comment]
@billspat I think it is probably best to not include the privacy statement for the resubmission. The exact warning here is pretty important as we don't want to get into trouble over any of this and if it just ins't there than that is OK. My thoughts are that we can add a privacy statement and disclaimer (basically saying we don't guarantee the results are correct) sometime between the last review and when the paper gets published

**Comment by billspat** [comment]
ok no problem.  the code is here in this branch and can stay until you are ready.    I'll move this issue to the next milestone.   Thanks for responding.

**Comment by billspat** [comment]
features and issues deferred for rewrite --closing here.
